server:
  port: 8020

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tharsikan/ResultShowConfigStore
          #username:
          #passphrase:
          search-paths:
            - '*service'