server:
  port: 8018

spring:
  application:
    name: membership

  datasource:
    url: jdbc:mysql://localhost:3306/resulService?createDatabaseIfNotExist=true
    username: root
    password: developer$12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update